 const TermsAndConditions = `These Terms of Service constitute a legally binding agreement between you ("Customer") and Arther, Inc. (together with its affiliates, “Arther”, "Company", “we,” “our” or “us”) governing your use of our products, services, and website (the “Site” and collectively with the foregoing, the “Services”).

 This agreement may be used in conjunction with an order form for Services ("Order Form").  The effective date of this agreement shall be the earlier of (i) the effective date set forth on the Order Form and (ii) the date the Customer first began using Company’s Services.
 
 YOU ACKNOWLEDGE AND AGREE THAT, BY CLICKING ON THE “I AGREE” OR SIMILAR BUTTON, REGISTERING FOR AN ACCOUNT, OR ACCESSING OR USING THE SERVICES, YOU ARE INDICATING THAT YOU HAVE READ, UNDERSTAND AND AGREE TO BE BOUND BY THESE TERMS OF SERVICE, WHETHER OR NOT YOU HAVE REGISTERED WITH THE SITE. IF YOU DO NOT AGREE TO THESE TERMS OF SERVICE, THEN YOU HAVE NO RIGHT TO ACCESS OR USE THE SERVICES.  These Terms of Service are effective as of the date you first click “I agree” (or similar button or checkbox) or use or access the Services, whichever is earlier.  If you accept or agree to these Terms of Service on behalf of your employer or another legal entity, you represent and warrant that (i) you have full legal authority to bind your employer or such entity to these Terms of Services; (ii) you have read and understand these Terms of Service; and (iii) you agree to these Terms of Service on behalf of the party that you represent and any permitted users of such party. In such event, “you” and “your” will refer and apply to your employer or such other legal entity.
 
 Any personal data you submit to the us or which we collect about you is governed by our Privacy Policy (“Privacy Policy”), available at https://cascade.io/privacy.  You acknowledge that by using the Services, you have reviewed the Privacy Policy.  The Privacy Policy is incorporated by reference into these Terms of Service and together form and are hereinafter referred to as this “Agreement.”
 
 PLEASE NOTE: THIS AGREEMENT GOVERNS HOW DISPUTES BETWEEN YOU AND CASCADE CAN BE RESOLVED. IT CONTAINS A BINDING AND FINAL ARBITRATION PROVISION AND CLASS ACTION WAIVER (SECTION 13). PLEASE READ CAREFULLY AS IT AFFECTS YOUR LEGAL RIGHTS, INCLUDING, IF APPLICABLE, YOUR RIGHT TO OPT OUT OF ARBITRATION.
 
 1. Our Services
 Our Services consist of data modeling, manipulation, analysis and publishing tools built that makes use of user-provided data.
 
 2. Account, Password and Security
 You must register with Cascade and create an account to use the Services (an “Account”) and as part of that process you will be requested to provide certain information, including without limitation your name and email address. By using the Services, you agree to provide true, accurate, current and complete information as prompted by the registration process and to maintain and promptly update the Account information to keep it accurate, current and complete. You are the sole authorized user of your Account. You are responsible for maintaining the confidentiality of any log-in, password, and Account number provided by you or given to you by Cascade for accessing the Services. You are solely and fully responsible for all activities that occur under your password or Account, even if not authorized by you. Cascade has no control over the use of any user’s Account and expressly disclaims any liability derived therefrom. Should you suspect that any unauthorized party may be using your password or Account or you suspect any other breach of security, you agree to contact Cascade immediately.
 
 The person signing up for the Services will be the contracting party (“Account Owner”) for the purposes of these Terms of Service and will be the person who is authorized to use any corresponding Account we provide to the Account Owner in connection with the Services; provided, however, that if you are signing up for the Services on behalf of your employer, your employer shall be the Account Owner. As the Account Owner, you are solely responsible for complying with these Terms of Service and only you are entitled to all benefits accruing thereto. Your Account is not transferable to any other person or account. You must immediately notify us of any unauthorized use of your password or identification or any other breach or threatened breach of our security or the security of your Account.  
 
 Subject to the terms of this agreement, Company will use commercially reasonable efforts to provide Customer Services. As part of the registration process, Customer will identify the individuals that should have access to the Platform, and Company reserves the right to review and approve such list prior to providing access to the Platform to such individuals (such approved individuals, “Users”); provided that such approval shall not be unreasonably withheld. Customer will provide Users’ email addresses to Company, and Company will invite such Users to access the Platform by email by first setting up an username and password for such User’s account. Company reserves the right to refuse registration of, or cancel usernames or passwords it deems inappropriate.
 
 Subject to the terms hereof, Company will provide Customer and its Users with reasonable technical support services in accordance with Company’s standard practice.
 
 3. User Content
 “User Content” is defined as any content, information, and materials that may be textual, audio, or visual that you provide, submit, upload, publish, or make otherwise available to the Services and other users.
 
 You agree that you are solely responsible for the User Content, User Content sent or transmitted by you or displayed or uploaded by you in using the Services, and for compliance with all laws applicable to the User Content, including, but not limited to, any laws requiring you to obtain the consent of a third party to use the User Content and to provide appropriate notices of third party rights. You represent and warrant that you have the right to upload the User Content to the Services and that such use does not violate or infringe on any rights of any third party. Under no circumstances will Cascade be liable in any way for any (a) User Content that is transmitted or viewed while using the Services,(b) errors or omissions in the User Content, or (c) any loss or damage of any kind incurred as a result of the use of, access to, or denial of access to User Content. Although Cascade is not responsible for any User Content, Cascade reserves the right to delete any User Content, at any time without notice to you, if Cascade becomes aware that it violates any provision of this Agreement or any law. You retain copyright and other rights you already hold in User Content.  
 
 Cascade acts merely as a passive conduit for your online distribution and publication of your User Content. You acknowledge and agree that Cascade:
 
 ·  Is not involved in the creation or development of User Content.
 
 ·  Disclaims any responsibility for User Content.
 
 ·  Cannot be liable for claims arising out of or relating to User Content.
 
 ·  Is not obligated to monitor, review, or remove User Content, but reserves the right to limit or remove User Content on the Services at its sole discretion.
 
 You hereby represent and warrant to Cascade that your User Content (i) will not be false, inaccurate, incomplete or misleading; (ii) will not infringe on any third party’s copyright, patent, trademark, trade secret or other proprietary right or rights of publicity, personality or privacy; (iii) will not violate any law ,statute, ordinance, or regulation (including without limitation those governing export control, consumer protection, unfair competition, anti-discrimination, false advertising, anti-spam or privacy); (iv) will not be defamatory, libelous, unlawfully threatening, or unlawfully harassing; (v) will not be obscene or contain pornography (including but not limited to child pornography) or be harmful to minors; (vi) will not contain any viruses, Trojan Horses, worms, time bombs, cancelbots or other computer programming routines that are intended to damage, detrimentally interfere with, surreptitiously intercept or expropriate any system, data or personal information; (vii) will not represent you being employed or directly engaged by or affiliated with Cascade or purport you to act as a representative or agent of Cascade; and (viii) will not create liability for Cascade or cause Cascade to lose (in whole or in part) the services of its ISPs or other suppliers.
 
 By making available any User Content through the Services, you hereby grant to Cascade an irrevocable, transferable, sublicensable (through multiple tiers), fully paid, royalty-free and worldwide right and license to use, copy, access, store, modify and display such User Content: to further Cascade’s legitimate interests in providing the Services; to provide, maintain and improve the Services; to perform such other actions as authorized by you in connection with your use of the Services; and such other purposes identified in the Privacy Policy. We do not claim any ownership rights in any such User Content and nothing in this Agreement will be deemed to restrict any rights that you may have to use and exploit any such User Content. Cascade will not access, view or process User Content, except (a) as provided for in this Agreement or the Privacy Policy; (b) as authorized or instructed by you; (c) as required to perform its obligations under this Agreement; or (d) as required by applicable law. Cascade has no other obligations with respect to User Content.
 
 `

 export default TermsAndConditions